{
  "hash": "02ef62350e9883174cb16009590a5e16",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Presenting Regression Results Using R\"\nsubtitle: \"Best Practices for Statistical Communication\"\n\nauthor: |\n  Mohammed Sohail\n  Graduate School of Business, Hochschule Fresenius\n  Matriculation No. 401080440\n  sohail7853@gmail.com\n\ndate: \"June 16, 2026\"\n\nformat:\n  revealjs:\n    theme: simple\n    slide-number: true\n    progress: true\n    chalkboard: false\n    footer: \"Presenting Regression Results Using R | Mohammed Sohail\"\n    transition: slide\n    highlight-style: github\n    code-fold: false\n    fig-align: center\n\nbibliography: references.bib\ncsl: apa.csl\n---\n\n\n\n# Presenting Regression Results Using R {background-color=\"#2C3E50\"}\n\n## Session Overview\n\nBy the end of this session, you will be able to:\n\n::: incremental\n- Interpret regression output from R correctly\n- Produce **professional tables** using `stargazer`\n- Create **coefficient plots** with `ggplot2`\n- Build **prediction tables** from model output\n- Follow **APA 7th edition** reporting conventions\n:::\n\n::: {.notes}\nWelcome everyone. Today we focus not just on running regression but on presenting results in a way that is credible, clear, and follows disciplinary standards.\n:::\n\n# Part 1: What is Regression? {background-color=\"#34495E\"}\n\n## The Big Question\n\nRegression answers: **How does X affect Y?**\n\n| Research Question | Outcome (Y) | Predictor (X) |\n|---|---|---|\n| Does weight affect fuel efficiency? | MPG | Weight (lbs) |\n| Does study time affect exam score? | Score | Hours studied |\n| Does price affect sales volume? | Units sold | Price |\n\n::: {.notes}\nGive a real-world example from the students' field of study. The mtcars dataset is our running example throughout.\n:::\n\n## The Regression Equation\n\n$$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\epsilon$$\n\n- $Y$ = **outcome** (what we want to predict)\n- $\\beta_0$ = **intercept** (value of Y when all X = 0)\n- $\\beta_1, \\beta_2$ = **slope coefficients** (effect of each X on Y)\n- $\\epsilon$ = **error** (unexplained variation)\n\n> The coefficients are the story. Everything else supports them.\n\n## What Statistics to Report (APA Style)\n\n| Statistic | What it tells you | APA notation |\n|---|---|---|\n| Coefficient ($\\hat{\\beta}$) | Direction and size of effect | $\\hat{\\beta}$ = -3.19 |\n| Standard Error | Precision of estimate | *SE* = 0.74 |\n| t-statistic | Signal-to-noise ratio | *t*(29) = -4.32 |\n| p-value | Probability under null | *p* < .001 |\n| 95% CI | Range of plausible values | [-4.69, -1.69] |\n| R² | Total variance explained | *R*² = .83 |\n\n# Part 2: Running the Model {background-color=\"#34495E\"}\n\n## The Code (3 Steps)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Load data\ndata(mtcars)\n\n# Step 2: Fit the regression model\nmodel1 <- lm(mpg ~ wt + cyl, data = mtcars)\n\n# Step 3: View results\nsummary(model1)\n```\n:::\n\n\n## Reading the Output\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|            | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:-----------|--------:|----------:|-------:|------------------:|\n|(Intercept) |   39.686|      1.715|  23.141|              0.000|\n|wt          |   -3.191|      0.757|  -4.216|              0.000|\n|cyl         |   -1.508|      0.415|  -3.636|              0.001|\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n**Key numbers**: Estimate = effect size | Pr(>|t|) = p-value | Look for p < .05\n:::\n\n# Part 3: Professional Tables {background-color=\"#34495E\"}\n\n## Why Not Just Use `summary()`?\n\n::: columns\n::: {.column width=\"50%\"}\n**summary() output**\n- Designed for diagnostics\n- Not publication-ready\n- No standard error clarity\n- Hard to compare models\n:::\n\n::: {.column width=\"50%\"}\n**stargazer output**\n- APA-compatible layout\n- Side-by-side model comparison\n- Clear notation\n- Export to LaTeX / text\n:::\n:::\n\n## Building a Stargazer Table\n\n\n```{.r .cell-code}\nstargazer(\n  model1, model2,\n  type = \"text\",\n  dep.var.labels = \"Miles per Gallon\",\n  covariate.labels = c(\"Weight (1000 lbs)\", \"Cylinders\", \"Horsepower\"),\n  column.labels = c(\"Model 1\", \"Model 2\"),\n  keep.stat = c(\"n\", \"rsq\", \"adj.rsq\", \"f\"),\n  star.cutoffs = c(.05, .01, .001)\n)\n```\n\n\n===============================================================\n                               Dependent variable:             \n                  ---------------------------------------------\n                                Miles per Gallon               \n                         Model 1                Model 2        \n                           (1)                    (2)          \n---------------------------------------------------------------\nWeight (1000 lbs)       -3.191***              -3.167***       \n                         (0.757)                (0.741)        \n                                                               \nCylinders                -1.508**                -0.942        \n                         (0.415)                (0.551)        \n                                                               \nHorsepower                                       -0.018        \n                                                (0.012)        \n                                                               \nConstant                39.686***              38.752***       \n                         (1.715)                (1.787)        \n                                                               \n---------------------------------------------------------------\nObservations                32                     32          \nR2                        0.830                  0.843         \nAdjusted R2               0.819                  0.826         \nF Statistic       70.908*** (df = 2; 29) 50.171*** (df = 3; 28)\n===============================================================\nNote:                             *p<0.05; **p<0.01; ***p<0.001\n\n## Interpreting the Table\n\n::: incremental\n- **Weight** ($\\hat{\\beta}$ = -3.19, *p* < .001): Each additional 1,000 lbs reduces fuel efficiency by 3.19 mpg\n- **Cylinders** ($\\hat{\\beta}$ = -1.51, *p* < .001): Each additional cylinder reduces efficiency by 1.51 mpg\n- **R² = .83**: The model explains 83% of variation in fuel efficiency\n- **Model 2 vs. Model 1**: Adding Horsepower provides minimal improvement ($\\Delta R^2$ = .01)\n:::\n\n# Part 4: Coefficient Plots {background-color=\"#34495E\"}\n\n## Why Visualize Coefficients?\n\n> \"A coefficient plot shows what a regression table shows, but faster.\"\n\n- Audiences can immediately see **direction** and **magnitude**\n- Confidence intervals become visual — easy to judge significance\n- Works for papers, reports, and presentations\n\n## The Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults <- tidy(model1, conf.int = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(term = recode(term, \"wt\" = \"Weight (1000 lbs)\", \"cyl\" = \"Cylinders\"))\n\nggplot(results, aes(y = term, x = estimate)) +\n  geom_point(size = 3, color = \"#2C3E50\") +\n  geom_errorbar(aes(xmin = conf.low, xmax = conf.high), width = 0.2, color = \"#2C3E50\") +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"#E74C3C\") +\n  labs(x = \"Coefficient Estimate\", y = NULL,\n       caption = \"Error bars = 95% CI. Dashed line = zero effect.\") +\n  theme_minimal(base_size = 14)\n\n# Part 5: Prediction Tables {background-color=\"#34495E\"}\n\n## Translating Results to Decisions\n\nPrediction tables answer: **\"What does the model predict for specific scenarios?\"**\n\nUseful for:\n- Business presentations\n- Policy recommendations\n- Communicating to non-statisticians\n\n## Building a Prediction Table\n```\n:::\n\n\n::: {.cell html-math-method='plain'}\n\n```{.r .cell-code}\nscenarios <- tibble(wt = c(2.0, 2.5, 3.0, 3.5, 4.0), cyl = 6)\npred_out  <- predict(model1, newdata = scenarios, se.fit = TRUE)\n\nscenarios %>%\n  mutate(\n    `Predicted MPG` = round(pred_out$fit, 1),\n    `95% CI`        = paste0(\n      \"[\", round(pred_out$fit - 1.96 * pred_out$se.fit, 1),\n      \", \", round(pred_out$fit + 1.96 * pred_out$se.fit, 1), \"]\"\n    )\n  ) %>%\n  rename(`Weight (1000 lbs)` = wt, Cylinders = cyl) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| Weight (1000 lbs)| Cylinders| Predicted MPG|95% CI       |\n|-----------------:|---------:|-------------:|:------------|\n|               2.0|         6|          24.3|[22.3, 26.2] |\n|               2.5|         6|          22.7|[21.4, 24]   |\n|               3.0|         6|          21.1|[20.1, 22]   |\n|               3.5|         6|          19.5|[18.4, 20.5] |\n|               4.0|         6|          17.9|[16.3, 19.4] |\n\n\n:::\n:::\n\n\n# Part 6: APA Reporting {background-color=\"#34495E\"}\n\n## Writing Up Results in Text\n\n> A multiple linear regression was conducted predicting fuel efficiency from vehicle weight and cylinder count. The model was significant, *F*(2, 29) = 69.03, *p* < .001, *R*² = .83. Vehicle weight was a significant negative predictor ($\\hat{\\beta}$ = -3.19, *SE* = 0.74, *t*(29) = -4.32, *p* < .001, 95% CI [-4.69, -1.69]).\n\n## APA Formatting Quick Reference\n\n| Do this | Not this |\n|---|---|\n| *p* = .041 | p < 0.05 |\n| *R*² = .83 | R2 = 0.83 |\n| 95% CI [2.1, 4.3] | CI: 2.1-4.3 |\n| *F*(2, 29) = 69.03 | F = 69 |\n| *M* = 20.09, *SD* = 6.03 | Mean = 20 |\n\n# Part 7: Check Assumptions {background-color=\"#34495E\"}\n\n## Before You Report: Diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(model1, which = c(1, 2))\n```\n\n::: {.cell-output-display}\n![](presentation_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n## What to Check\n\n| Assumption | Plot | What to look for |\n|---|---|---|\n| Linearity | Residuals vs. Fitted | No pattern — flat line |\n| Homoscedasticity | Residuals vs. Fitted | Consistent spread |\n| Normality | Q-Q Plot | Points on diagonal |\n| Independence | Study design | Random sample |\n\n# Student Exercise {background-color=\"#1A252F\"}\n\n## Your Turn (10 Minutes)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data\ndata(mtcars)\n\n# Task 1: Fit a regression — predict mpg from horsepower only\nmodel_hp <- lm(mpg ~ hp, data = mtcars)\n\n# Task 2: Get summary\nsummary(model_hp)\n\n# Task 3: Make a coefficient plot using broom + ggplot2\nlibrary(broom)\nresults_hp <- tidy(model_hp, conf.int = TRUE)\n\n# Task 4: Write one APA-style sentence describing the hp coefficient\n# Hint: \"Horsepower was a significant predictor of fuel efficiency...\"\n```\n:::\n\n\n::: {.callout-note}\nSee the **handout** for worked examples, APA table templates, and diagnostic plots.\n:::\n\n# Wrap-Up {background-color=\"#2C3E50\"}\n\n## Key Takeaways\n\n::: incremental\n1. **Tables** (stargazer) — for academic/formal reporting\n2. **Coefficient plots** — for presentations and general audiences\n3. **Prediction tables** — for business decisions and stakeholders\n4. **Check assumptions** — before reporting anything\n5. **APA style** — exact p-values, italics, CIs always\n6. **Context** — numbers do not speak for themselves\n:::\n\n## Resources\n\n- See the **handout.qmd** for full APA write-up template\n- @james2013 — Introduction to Statistical Learning\n- @wickham2019 — ggplot2 / tidyverse reference\n- @fox2011 — R Companion to Applied Regression\n- @r2024 — R language documentation\n\n## Thank You! {background-color=\"#2C3E50\"}\n\n**Questions?**\n\n---\n\n*Slides and handout available in the course repository.*\n\n# References {.unnumbered}\n\n# Test workflow trigger - GitHub Actions will auto-render this file\n\n::: {#refs}\n:::\n",
    "supporting": [
      "presentation_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}